#%RAML 1.0 ResourceType

description: Collection of <<resourcePathName>>

get:
  description: Returns a list of all <<resourcePathName>>
  responses:
    200:
      body:
        application/json:
          example: <<exampleSuccess>>
post:
  description: Requests the creation of a new <<resourcePathName | !singularize>>
  body:
    application/json:
      type: <<resourcePathName | !singularize>>
      examples: <<examplesPostBody>>
  responses:
    204:
      description: The <<resourcePathName | !singularize>> was created successfully
