#%RAML 1.0
title: Best Linux Distribution API
baseUri: https://best.distro/{version}
version: v1
description: A voting system for the best Linux distribution
documentation:
  - !include docs/legal.raml
  - !include docs/authentication.raml

types:
  distribution:
    type: object
    properties:
      name:
        type: string
      version:
        pattern: ^(\d+\.)?(\d+\.)?(\*|\d+)$
  vote:
    type: object
    properties:
      distribution_name:
        type: string
      total:
        type: number
        required: false

resourceTypes:
  collection: !include resourceTypes/collection.raml

/distributions:
  type:
    collection:
      exampleSuccess: !include samples/distributions/all.sample
      examplesPostBody:
        fedora: !include samples/distributions/fedora.sample
        arch: !include samples/distributions/arch.sample

/votes:
  type:
    collection:
      exampleSuccess: !include samples/votes/all.sample
      examplesPostBody:
        ubuntu: !include samples/votes/ubuntu.sample