#%RAML 1.0
title: Best Linux Distribution API
baseUri: https://best.distro/{version}
version: v1
description: A voting system for the best Linux distribution
documentation:
  - !include docs/legal.raml
  - !include docs/authentication.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml

/distributions:
  type:
    collection:
      exampleCollection: !include samples/distributions.sample
      exampleItem: !include samples/distribution.sample