#%RAML 1.0
title: Best Linux Distribution API
baseUri: https://best.distro/
version: v1

/environments:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              -
                name: Ubuntu
                version: 22.10
              -
                name: Linux Mint
                version: 21