#%RAML 1.0
title: Best Linux Distribution API
baseUri: https://best.distro/
version: v1
description: A voting system for the best Linux distribution
documentation:
  - title: Legal
    content: See our [legal documents](http://best.distro/legal)
  - title: How to create a new distribution
    content: |
      #### Authentication
      The API uses `API keys` to authenticate requests. You can view and manage your `API keys` in the Dashboard.

/distributions:
  description: Collection of distributions
  get:
    description: Returns a list of all distributions
    responses:
      200:
        body:
          application/json:
            example:
              -
                name: Ubuntu
                version: 22.10
              -
                name: Linux Mint
                version: 21
  post:
    description: Requests the creation of a new distribution
    body:
      application/json:
        properties:
          name:
            type: string
          version:
            type: number
            format: float
        examples:
          fedora:
            name: Fedora
            version: 36
          arch:
            name: Arch Linux
            version: 2022.10.01
    responses:
        204:
          description: The distribution was created successfully